apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-health-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-health-app
  template:
    metadata:
      labels:
        app: node-health-app
    spec:
      containers:
        - name: node-health-app
          image: node-health-app:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health/startup
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
